### ISSUE TITLE
Column Doesn't Exist In EXT_OP_Invoice 

### ISSUE THREAD

**Issue by siluski** [SAP-samples/btp-procurement-data-extractor#1]
Hello, while working with the Invoice view template with the Operational Reporting For Procurement API, we're facing the below issue. 

When running a, "create job," on the view template, "EXT_OP_Invoice," the job is created, a file is imported and records begin to get modified in the DB. However, when it goes to process the files and finish the job, I see the following error :

Error while processing file Fljq0ux6g.zip for job e644da28-e572-4de6-8614-6c103fb50ab51688579873655 details: error: column "procurementunit_uniquename" of relation "sap_ariba_invoice_lineitem_splitaccountings" does not exist

The “unieuqname,” property appears to be mentioned for other attributes of entities within the Invoice.cds file. Does the "procurementunit_uniquename,” attribute not have to be named in the cds view? Could we have created the viewtemplate incorrectly in the Ariba realm? 

![Split accountings Entity](https://github.com/SAP-samples/btp-procurement-data-extractor/assets/47801828/442bc121-7b00-4245-8ffe-2779a13dfa8f)

![Invoice uniquename](https://github.com/SAP-samples/btp-procurement-data-extractor/assets/47801828/b5102877-48bc-4a9a-a521-b28f4d36d0ce)
32)
![Other uniquenames](https://github.com/SAP-samples/btp-procurement-data-extractor/assets/47801828/50aa3d81-3294-4f06-bf23-8f7225caca9a)

**Comment by swfuchs** [comment]
Hi @siluski,

this was already fixed through commit https://github.com/SAP-samples/btp-procurement-data-extractor/commit/2210196a640cee9143d387edf8a83b3a510a5e90 

I'd suggest you fetch the latest, update your instance and retry
