### ISSUE TITLE
EXT_OP_Contracts not returning data 

### ISSUE THREAD

**Issue by siluski** [SAP-samples/btp-procurement-data-extractor#2]
Hello, when working with the EXT_OP_Contracts view template we're facing the below issue.

When creating and running a job on the EXT_OP_Contract view template, it is able to create the job, execute and complete the job, and write/alter records in the DB.

However, when we run a "GET," on the Contracts SAC endpoint : {{appurl}}/sac/Contracts, no data is returned.

Is there a different endpoint we need to use to access the Contract data? 

![Job on Contracts Created](https://github.com/SAP-samples/btp-procurement-data-extractor/assets/47801828/cb7715fb-b372-4c10-9a99-aff807dc013f)

![Contract job completed](https://github.com/SAP-samples/btp-procurement-data-extractor/assets/47801828/005a4443-dcfc-403a-97c2-81ef44571d35)

![Contract job file downloaded](https://github.com/SAP-samples/btp-procurement-data-extractor/assets/47801828/43e2e9d3-0e93-4bac-8e10-5651a08a9f8e)

![Contract job affected rows](https://github.com/SAP-samples/btp-procurement-data-extractor/assets/47801828/84edfd29-4017-487e-a16f-1bf9455bd07f)

![No contract data returned](https://github.com/SAP-samples/btp-procurement-data-extractor/assets/47801828/dc4e78be-7086-4e28-9548-45692b6d65b9)

**Comment by swfuchs** [comment]
Hi @siluski , the "Contracts" entity in the oData service is referencing to another view template. In fact, this is associated to the Analytical Reporting API.

The relevant object associated to the view template "EXT_OP_Contract" is "**ContractsOS**" along with its sub-entities. This however is not present in the oData service. All you need to do is to expose these entities as part of the oData service
