### ISSUE TITLE
'datasphere' branch: Postman can't create job - Error while starting job

### ISSUE THREAD

**Issue by st-gr** [SAP-samples/btp-procurement-data-extractor#6]
### Error while starting job
When I am trying to create a job with postman I am getting a HTTP 200, but the application reports an error:
![image](https://github.com/user-attachments/assets/66929c13-2155-428d-8920-ad4bd06c94b4)

The application log states:
`,"msg":"Error while processing API call : AxiosError: Request failed with status code 404 `

Is this originating from the Ariba API?

How can I further analyze this? 

### Notes on destination configuration
The 'apikey' property should ideally be 'apiKey' so that the key would be masked in the UI of the destination service. Unfortunately, the code requires the lower-case property key 'apikey'.
[See jobHandler.js](https://github.com/SAP-samples/btp-procurement-data-extractor/blob/datasphere/srv/handlers/jobs/jobHandler.js), line 50:
`        //Destination validation `
`        if(!oDestination || !oDestination.originalProperties.destinationConfiguration.apikey) {`

As it turns out one has to configure for the client secret only the password part of the otherwise base64 encoded client id and secret:

E. g. secret: NDI0NzExMTItc29tZS11dWlkLWM1NzYtMTIzNDU2Nzg5MDEyOlN1cGVyU2VjcmV0UGFzc3dvcmQxMjM0NTY3ODkwMTIz
Decoded:
42471112-some-uuid-c576-123456789012:**SuperSecretPassword1234567890123**

![image](https://github.com/user-attachments/assets/aef5d2c8-6f7d-4303-95ce-942491a4ecc2)

**Comment by grundmanns-cosd** [comment]
The above issue can be marked as resolved.

Make sure that the view template used in the job creation exists on Ariba. This will resolve the `AxiosError: Request failed with status code 404`.
