### ISSUE TITLE
Issue with UAA Service Instance

### ISSUE THREAD

**Issue by jainmrce** [SAP-samples/btp-procurement-data-extractor#9]
while deploying the app, we got an error saying could not find service instance for UAA.

"Error creating application null (Error parsing xs-security.json data: Error reading service instance ID for service instance 'btp-procurement-data-extractor-jobscheduler' from cloud controller: 'Cannot find service instance for space id 'ae9e0c39-9f5d-4f08-a816-315eac850cd0' and service 'btp-procurement-data-extractor-jobscheduler'.')",

We created UAA service instance manually and tried to redeploy, got below error:

Couldn't update service instance 'btp-procurement-data-extractor-uaa'.
Instance ID: 341d1943-d889-4cc4-b0e6-ea6df8331503

Updating service "btp-procurement-data-extractor-uaa" failed: Could not find xsapp entry for btp-procurement-data-extractor!t333227

**Comment by swfuchs** [comment]
Hello @jainmrce , you'll need to delete the UAA service instance and re-create it. This should solve the problem as the Job Scheduler instance need to be created prior to UAA service instance
